version: '3.8'

services:

  myapp-mariadb:
    image: mariadb:10.1
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ramdisk
      - MYSQL_USER=java
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - 3307:3306
  #    volumes:
  #      - /var/lib/mysql/ramdisk:/var/lib/mysql/ramdisk

  fake-smtp-server:
    image: gessnerfl/fake-smtp-server
    ports:
      - 5080:5080
      - 5025:5025


  myapp-main:
    image: ollysk/hexarepo:hexaport
    restart: on-failure
    depends_on:
      - myapp-mariadb
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=myapp-mariadb
      - DATABASE_USER=java
      - DATABASE_PASSWORD=password
      #- DATABASE_NAME=spring
      - DATABASE_PORT=3307

#  ./gradlew build
#  docker build -t ollysk/hexarepo:hexaport .
#  #docker run -p 8080:8080 creator
#  docker-compose up